### PR TITLE
Fix: Do not treat colons as delimiters

### PR DESCRIPTION
**Pull request by PatrickBaus**
The default settings of the Python [ConfigParser.RawConfigParser](https://docs.python.org/3.11/library/configparser.html#rawconfigparser-objects) treats the colon as a delimiter and there is no way to escape these delimiters. This is problematic because, for example, the [IGNORE_COLUMNS] section uses keys to identify the columns to drop.

KiCost uses columns that start with _kicost:_ for [custom data](https://hildogjr.github.io/KiCost/docs/_build/singlehtml/index.html#custom-part-data). These columns can therefore not be put on the ignore list.

I propose to remove the colon as a delimiter. I know this might break config files out there, but the examples given in the documentation only use the equals sign as a delimiter, so I suppose the ill effects will be limited.

### CODE REVIEW

**Comment by set-soft** [comment]
Hi @PatrickBaus !
What about something like this:
```python
        # Read out ignored-rows
        if self.SECTION_IGNORE in cf.sections():
            self.ignore = []
            for k, v in cf.items(self.SECTION_IGNORE):
                self.ignore.append((k if v is None else k+':'+v).lower())
```
This will allow _kicost:var_, and won't break other stuff. 

It won't allow _xxx=yyy_, but the same applies to your patch.

**Comment by PatrickBaus** [comment]
Hi,
I don't think there is an easy way to do this properly. I had thought about this as well, but I would rather fail hard when using the (previously) undocumented colon as a delimiter, than concatenating the key, value pairs.

Concatenating them has a, in my opinion, the unexpected side effect that both `foo=bar` and `foo:bar` parse to _foo:bar_ because the parser does not allow to distinguish between the delimiters. For the user, this will make no sense at all without looking at the code. I do know that an equals sign should not be used in this section, but Murphy says otherwise and something like that introduces hard to debug problems.

I therefore believe dropping support for the undocumented colon is the lesser evil.

**Comment by set-soft** [comment]
> Hi, I don't think there is an easy way to do this properly. I had thought about this as well, but I would rather fail hard when using the (previously) undocumented colon as a delimiter, than concatenating the key, value pairs.

Why? The `:` seems to be valid separator for INI files. I don't like it, in fact I would never use INI files. KiBot implements all of this functionality, and much more, using YAML.

> Concatenating them has a, in my opinion, the unexpected side effect that both `foo=bar` and `foo:bar` parse to _foo:bar_ because the parser does not allow to distinguish between the delimiters. For the user, this will make no sense at all without looking at the code.  I do know that an equals sign should not be used in this section, but Murphy says otherwise and something like that introduces hard to debug problems.

This can be solved with a warning. For me what doesn't make sense is to try to define a field with "=".

> I therefore believe dropping support for the undocumented colon is the lesser evil.

I don't agree.

With your patch:
- Rare INI files using `:` will be rejected (-)
- Entries with `:` in the *IGNORE_COLUMNS* will work perfectly (+)
- Entries with `=` in the *IGNORE_COLUMNS* will have real problems, they'll be truncated (-) [This problem can be attenuated adding a warning]

With the patch I proposed (and a warning):
- Rare INI files using `:` will work (+)
- Entries with `:` in the *IGNORE_COLUMNS* will work perfectly (+) [The user will get a warning asking to double check it]
- Entries with `=` in the *IGNORE_COLUMNS* won't work (-), but the user will get a clue about the problem.

**Comment by PatrickBaus** [comment]
@set-soft I have been this PR some thought lately and your approach deals with more corner cases. I would like to tweak it a bit though and propose the following implementation:

```python
        # Read out ignored-rows
        if self.SECTION_IGNORE in cf.sections():
            self.ignore = [
                key.lower() if value is None else (key+value).lower() for key, value in cf.items(self.SECTION_IGNORE)
            ]
```
This solution is closer to an escape mechanism and requires to repeat the delimiter (although using either `:` or `=` works just as well).

In order to drop the column `kicost:pricing`, one would use:

```
[IGNORE_COLUMNS]
kicost::pricing
```

This should of course be accompanied by some documentation in the readme (which I will gladly do if desired). Additionally, the fix needs to be applied to `[COLUMN_ORDER]`, `[GROUP_FIELDS]` and `[REGEX_INCLUDE]`.

Do let me know what you think about it.

**Comment by set-soft** [comment]
Hi @PatrickBaus !
Long time ... so I might be confused. Why do you think is better something that must be explained instead of something that works out of the box?

**Comment by PatrickBaus** [comment]
Using the other solution would forcefully rewrite `foo=bar` to `foo:bar` and there is no way to fix this as a user. While this might be a corner case for the column names, it is more probable and annoying when considering the `[REGEX_INCLUDE]`/`[REGEX_EXCLUDE]` section.

**Comment by PatrickBaus** [comment]
@set-soft  Hi, did you get a chance to read my comment? It would be so great to get this issue fixed.

**Comment by set-soft** [comment]
Hi @PatrickBaus !

Take a look at cef5ff5ad2b3f6d2402bba9b68b0b75cf745374f I think this is the best solution.

Most people won't need this option and things will work as usual, people using KiCost special fields will just need to add a command line option. Do you see any thing not covered by this patch?

**Comment by PatrickBaus** [comment]
@set-soft Cool, thanks for the fix. Looks good to me. I will close this PR then.

**Pull request closed without merging**
